import { 
  LayoutDashboard, 
  Users, 
  Globe, 
  List, 
  Settings, 
  ShieldCheck, 
  CreditCard, 
  Share2, 
  LogOut, 
  User,
  Bell,
  HelpCircle,
  Menu,
  CheckCircle,
  XCircle,
  AlertTriangle,
  ArrowUp,
  ArrowDown,
  Check,
  Clock,
  Database,
  Activity,
  Mail,
  Server,
  Lock,
  Key,
  Trash2,
  Copy,
  Search,
  ChevronLeft,
  ChevronRight,
  Filter,
  RefreshCw,
  UserPlus,
  Loader2,
  AlertCircle
} from "lucide-react";

// Export all icons together
export const Icons = {
  dashboard: LayoutDashboard,
  users: Users,
  globe: Globe,
  list: List,
  settings: Settings,
  shield: ShieldCheck,
  creditCard: CreditCard,
  share: Share2,
  logout: LogOut,
  user: User,
  bell: Bell,
  help: HelpCircle,
  menu: Menu,
  checkCircle: CheckCircle,
  xCircle: XCircle,
  alertTriangle: AlertTriangle,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  check: Check,
  clock: Clock,
  database: Database,
  activity: Activity,
  mail: Mail,
  server: Server,
  lock: Lock,
  key: Key,
  trash: Trash2,
  copy: Copy,
  search: Search,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  filter: Filter,
  refresh: RefreshCw,
  userPlus: UserPlus,
  loader: Loader2,
  alertCircle: AlertCircle,
  // Add an icon for activity items that don't match any specific type
  activityIcon: Activity,
};
